services:
  server:
    build: ./
    ports: 
     - 3000:3000
    restart: always
    volumes:
      - ./:/hack_train
      - /hack_train/node_modules
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 2000:5432
    environment:
      - POSTGRES_PASSWORD=Nk%jTWxMtP.1
    volumes:
      - /postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - 6000:6379